{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ template "kube2iam.fullname" . }}-metrics
  labels:
    app: {{ template "kube2iam.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "kube2iam.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: metrics
      {{- if .Values.prometheus.metricsPort }}
      port: {{ .Values.prometheus.metricsPort }}
      targetPort: {{ .Values.prometheus.metricsPort }}
      {{- else }}
      port: {{ .Values.host.port }}
      targetPort: {{ .Values.host.port }}
      {{- end }}
      protocol: TCP
{{ end }}
